### ISSUE TITLE
Application for todo-cli-app

### ISSUE THREAD

**Issue by wujackwill** [1Password/for-open-source#991]
### Account URL

https://jackwill.1password.com/

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

todo-cli-app

### Short description

yet another todo CLI app written in Rust

### Number of team members/core contributors

2

### Homepage URL

https://github.com/wujackwill/todo-cli-app

### Repository URL

https://github.com/wujackwill/todo-cli-app

### License type

MIT

### License URL

https://github.com/wujackwill/todo-cli-app/blob/master/LICENSE

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

jackwill

### Email

wujackwill@outlook.com

### Project role

Founder or Owner

### Can we contact you?

- [X] Yes, you may contact me
